# Vercel CI/CD Pipeline Workflow
# NEXUS-PRIME Workflow Definition

name: vercel-ci-cd
version: "1.0.0"
description: "Complete CI/CD pipeline with GitHub Actions integration for Vercel"
category: ci-cd
trigger:
  - git_push
  - pull_request

metadata:
  author: "NEXUS-PRIME"
  created: "2025-01-15"
  tags: ["vercel", "ci-cd", "github-actions", "automation"]

# Required agents for this workflow
agents:
  primary:
    - DEPLOY-MASTER
  support:
    - PREVIEW-MASTER
    - METRICS-WATCH
    - ENV-CONFIG

# GitHub Actions workflow template
github_actions:
  path: .github/workflows/vercel-deploy.yml
  content: |
    name: Vercel Deploy

    on:
      push:
        branches: [main, master]
      pull_request:
        types: [opened, synchronize, reopened]

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    jobs:
      # Lint and Type Check
      quality:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: Setup Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '20'
              cache: 'npm'

          - name: Install dependencies
            run: npm ci

          - name: Run linter
            run: npm run lint --if-present

          - name: Type check
            run: npm run typecheck --if-present || npm run type-check --if-present || true

      # Run Tests
      test:
        runs-on: ubuntu-latest
        needs: quality
        steps:
          - uses: actions/checkout@v4

          - name: Setup Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '20'
              cache: 'npm'

          - name: Install dependencies
            run: npm ci

          - name: Run tests
            run: npm test -- --passWithNoTests --coverage

          - name: Upload coverage
            uses: codecov/codecov-action@v3
            if: always()
            with:
              fail_ci_if_error: false

      # Preview Deployment (PRs)
      deploy-preview:
        runs-on: ubuntu-latest
        needs: [quality, test]
        if: github.event_name == 'pull_request'
        environment:
          name: preview
          url: ${{ steps.deploy.outputs.url }}
        steps:
          - uses: actions/checkout@v4

          - name: Install Vercel CLI
            run: npm install -g vercel@latest

          - name: Pull Vercel Environment
            run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

          - name: Build Project
            run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

          - name: Deploy Preview
            id: deploy
            run: |
              url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
              echo "url=$url" >> $GITHUB_OUTPUT

          - name: Comment on PR
            uses: actions/github-script@v7
            with:
              script: |
                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: `## Preview Deployment\n\n:rocket: Preview deployed to: ${{ steps.deploy.outputs.url }}`
                })

      # Production Deployment (main branch)
      deploy-production:
        runs-on: ubuntu-latest
        needs: [quality, test]
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        environment:
          name: production
          url: ${{ steps.deploy.outputs.url }}
        steps:
          - uses: actions/checkout@v4

          - name: Install Vercel CLI
            run: npm install -g vercel@latest

          - name: Pull Vercel Environment
            run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

          - name: Build Project
            run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

          - name: Deploy Production
            id: deploy
            run: |
              url=$(vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }})
              echo "url=$url" >> $GITHUB_OUTPUT

          - name: Create Release Tag
            if: success()
            run: |
              git tag "deploy-$(date +%Y%m%d-%H%M%S)"
              git push --tags
            continue-on-error: true

      # Lighthouse Audit
      lighthouse:
        runs-on: ubuntu-latest
        needs: deploy-preview
        if: github.event_name == 'pull_request'
        steps:
          - uses: actions/checkout@v4

          - name: Lighthouse CI
            uses: treosh/lighthouse-ci-action@v10
            with:
              urls: |
                ${{ needs.deploy-preview.outputs.url }}
              configPath: ./lighthouserc.json
              uploadArtifacts: true
              temporaryPublicStorage: true

# Setup instructions
setup:
  steps:
    - name: "Create GitHub Secrets"
      description: |
        Add these secrets to your GitHub repository:
        - VERCEL_TOKEN: Your Vercel API token
        - VERCEL_ORG_ID: Your Vercel organization ID
        - VERCEL_PROJECT_ID: Your Vercel project ID

        Get these values by running:
        - vercel link
        - cat .vercel/project.json

    - name: "Create workflow file"
      action: bash
      command: |
        mkdir -p .github/workflows
        # Copy the github_actions content above to .github/workflows/vercel-deploy.yml

    - name: "Add Lighthouse config (optional)"
      action: bash
      command: |
        cat > lighthouserc.json << 'EOF'
        {
          "ci": {
            "assert": {
              "assertions": {
                "categories:performance": ["warn", {"minScore": 0.8}],
                "categories:accessibility": ["error", {"minScore": 0.9}],
                "categories:best-practices": ["warn", {"minScore": 0.8}],
                "categories:seo": ["warn", {"minScore": 0.8}]
              }
            }
          }
        }
        EOF

# Alternative: GitLab CI
gitlab_ci:
  path: .gitlab-ci.yml
  content: |
    stages:
      - test
      - deploy

    variables:
      VERCEL_TOKEN: $VERCEL_TOKEN
      VERCEL_ORG_ID: $VERCEL_ORG_ID
      VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID

    test:
      stage: test
      image: node:20
      script:
        - npm ci
        - npm run lint --if-present
        - npm test -- --passWithNoTests

    deploy-preview:
      stage: deploy
      image: node:20
      script:
        - npm install -g vercel
        - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
        - vercel build --token=$VERCEL_TOKEN
        - vercel deploy --prebuilt --token=$VERCEL_TOKEN
      only:
        - merge_requests

    deploy-production:
      stage: deploy
      image: node:20
      script:
        - npm install -g vercel
        - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
        - vercel build --prod --token=$VERCEL_TOKEN
        - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
      only:
        - main
        - master
