// Supabase Client for Next.js
// Generated by NEXUS-PRIME Supabase Plugin

import { createBrowserClient } from '@supabase/ssr'
import { createServerClient, type CookieOptions } from '@supabase/ssr'
import { cookies } from 'next/headers'
import type { Database } from '@/types/supabase'

// Environment variables
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

/**
 * Create a Supabase client for browser/client components
 */
export function createClient() {
  return createBrowserClient<Database>(supabaseUrl, supabaseAnonKey)
}

/**
 * Create a Supabase client for server components
 * Use in: Server Components, Route Handlers, Server Actions
 */
export async function createServerComponentClient() {
  const cookieStore = await cookies()

  return createServerClient<Database>(supabaseUrl, supabaseAnonKey, {
    cookies: {
      getAll() {
        return cookieStore.getAll()
      },
      setAll(cookiesToSet) {
        try {
          cookiesToSet.forEach(({ name, value, options }) =>
            cookieStore.set(name, value, options)
          )
        } catch {
          // Called from Server Component - ignore
        }
      },
    },
  })
}

/**
 * Create a Supabase client for middleware
 */
export function createMiddlewareClient(request: Request) {
  let response = new Response()

  const supabase = createServerClient<Database>(supabaseUrl, supabaseAnonKey, {
    cookies: {
      getAll() {
        return request.headers.get('cookie')?.split('; ').map(cookie => {
          const [name, value] = cookie.split('=')
          return { name, value }
        }) ?? []
      },
      setAll(cookiesToSet) {
        cookiesToSet.forEach(({ name, value, options }) => {
          response.headers.append('Set-Cookie', `${name}=${value}; Path=/`)
        })
      },
    },
  })

  return { supabase, response }
}

/**
 * Get the current user (server-side)
 */
export async function getUser() {
  const supabase = await createServerComponentClient()
  const { data: { user } } = await supabase.auth.getUser()
  return user
}

/**
 * Get the current session (server-side)
 */
export async function getSession() {
  const supabase = await createServerComponentClient()
  const { data: { session } } = await supabase.auth.getSession()
  return session
}

/**
 * Require authentication - throws if not authenticated
 */
export async function requireAuth() {
  const user = await getUser()
  if (!user) {
    throw new Error('Authentication required')
  }
  return user
}
